# https://gist.github.com/y0ssar1an/df2dab474520c4086926f672c52db139
# This is a weird way of telling Travis to use the fast container-based test
# runner instead of the slow VM-based runner.
sudo: false
language: go

go:
  - 1.9.x
  - 1.10.x
  - master

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

before_script:
  - go get github.com/mdaliyan/govert

script:
   - go test -v -race ./...  # Run all the tests with the race detector enabled
